<div class="w-full bg-black border-t-2 border-t-violet-600 ">
    <div class="flex justify-center m-auto">
        <div class="flex items-center">
            <img width="120em" src="https://fo4.garena.vn/wp-content/themes/fifa-online-4/img/logos.png" alt="">
        </div>
        <p class="text-xs text-zinc-500 leading-3 w-3/4 m-10 text-center">© 201​8​ ELECTRONIC ARTS INC. EA, EA SPORTS, AND
            THE EA SPORTS LOGO ARE
            TRADEMARKS
            OF ELECTRONIC ARTS INC.
            OFFICIAL FIFA LICENSED PRODUCT. © FIFA NAME AND FIFA'S OFFICIAL LICENSED PRODUCT LOGO ARE COPYRIGHTS AND/OR
            TRADEMARKS OF FIFA. ALL RIGHTS RESERVED. MANUFACTURED UNDER LICENSE BY ELECTRONIC ARTS INC. THE USE OF REAL
            PLAYER NAMES AND LIKENESSES IS AUTHORIZED BY FIFPRO COMMERCIAL ENTERPRISES BV. THE PREMIER LEAGUE LOGO © THE
            FOOTBALL ASSOCIATION PREMIER LEAGUE LIMITED 2018. THE PREMIER LEAGUE LOGO IS A TRADEMARK OF THE FOOTBALL
            ASSOCIATION PREMIER LEAGUE LIMITED WHICH IS REGISTERED IN THE UK AND OTHER JURISDICTIONS. THE PREMIER LEAGUE
            CLUB LOGOS ARE COPYRIGHT WORKS AND REGISTERED TRADEMARKS OF THE RESPECTIVE CLUBS. ALL ARE USED WITH THE KIND
            PERMISSION OF THEIR RESPECTIVE OWNERS. MANUFACTURED UNDER LICENSE FROM THE FOOTBALL ASSOCIATION PREMIER
            LEAGUE
            LIMITED. NO ASSOCIATION WITH NOR ENDORSEMENT OF THIS PRODUCT BY ANY PLAYER IS INTENDED OR IMPLIED BY THE
            LICENSE
            GRANTED BY THE FOOTBALL ASSOCIATION PREMIER LEAGUE LIMITED TO ELECTRONIC ARTS. ALL OTHER TRADEMARKS ARE THE
            PROPERTY OF THEIR RESPECTIVE OWNERS.
        </p>
        <div class="flex items-center"><img width="120em"
                src="https://fo4.garena.vn/wp-content/themes/fifa-online-4/img/icon-age.png" alt=""></div>
    </div>
</div>
